### ISSUE TITLE
Mike Assante

### ISSUE THREAD

**Issue by attritionorg** [restincode/restincode#10]
https://www.csoonline.com/article/3403656/mike-assantes-lasting-impact-on-critical-infrastructure-security-and-me.html

**Comment by mubix** [comment]
Thanks!
- Twitter Link - https://twitter.com/assante_michael

**Comment by DavBatz** [comment]
https://www.prnewswire.com/news-releases/michael-j-assante-awarded-sans-ics-lifetime-achievement-award-300616669.html

**Comment by mauvehed** [comment]
Dupe of #61
