### ISSUE TITLE
Péter Szőr

### ISSUE THREAD

**Issue by mikkohypponen** [restincode/restincode#131]
Péter Szőr (17 July 1970 – 12 November 2013) was a computer virus researcher. He was also hacker, and entrepreneur and succesful author. Originally from Hungary, he worked in Finland and the United States.

**Comment by mauvehed** [comment]
Thanks, Mikko.

**Comment by mikkohypponen** [comment]
![peter_szor_1998](https://user-images.githubusercontent.com/1636990/76754129-46d91100-678a-11ea-8d13-13a510044a7f.jpg) Peter Szor in 1998

**Comment by mikkohypponen** [comment]
[Book: The Art of Computer Virus Research and Defense, by Péter Szőr](https://www.amazon.com/gp/product/0321304543/ref=dbs_a_def_rwt_hsch_vapi_taft_p1_i0)

**Comment by mikkohypponen** [comment]
[The Peter Szor award at the annual Virus Bulletin Conference](https://www.virusbulletin.com/blog/2014/09/windigo-research-wins-first-annual-p-ter-sz-r-award)

**Comment by mikkohypponen** [comment]
[In memoriam: Péter Ször 1970-2013](https://www.virusbulletin.com/virusbulletin/2013/12/memoriam-p-ter-sz-r-1970-2013)

**Comment by mikkohypponen** [comment]
[In memoriam: Péter Ször 1970-2013](https://www.virusbulletin.com/virusbulletin/2013/12/memoriam-p-ter-sz-r-1970-2013)

**Comment by mikkohypponen** [comment]
[Peter on Wikipedia](https://en.wikipedia.org/wiki/P%C3%A9ter_Sz%C5%91r)
