### ISSUE TITLE
Jerrod Bates

### ISSUE THREAD

**Issue by peterclemenko** [restincode/restincode#253]
Please fill out as much information as you can. No fields are required, but the more you can provide the better.

**General Info**

- First name: Jerrod
- Last name: Bates
- Birth Year: 1974
- Death Year: 2023, Sep 14
- Link to Obituary: https://www.legacy.com/us/obituaries/baytobaynews-de/name/jerrod-bates-obituary?id=53151891
- Group Affiliations: Del Tech, Wilmington University, US Cyber Challenge
- URL to main photo (or attach to Issue): https://cache.legacy.net/legacy/images/cobrands/baytobaynews-de/photos/Image-18791_20230920.jpgx?w=320&h=434&option=3
- Description of person and/or activities:  Jerrod Bates was a cybersecurity teacher in Delaware who inspired a lot of students to get active in the community and actually taught infosec right. He was active in conferences, getting students to conferences, and also getting students in places like US Cyber Challenge. He was a great teacher and a great person. He will be missed.

**Social Media Links**

- LinkedIn: https://www.linkedin.com/in/jerrod-bates-mba-cissp-ceh-3853a085/
- Facebook: https://www.facebook.com/jerrod.bates.9

**Contributions**
Repeat as many times as needed

- Project name: infosec teacher
- Project Description: He inspired a lot of students to get active in the community and actually taught infosec right.

**Comment by mauvehed** [comment]
Thank you 💜
