### ISSUE TITLE
Social Media Links Not Visible

### ISSUE THREAD

**Issue by aghassemlouei** [restincode/restincode#283]
**Describe the bug**
None of the links in the "socialmedialinks" section renders on any page. 

**To Reproduce**

1. View [existing profile json](https://github.com/restincode/restincode/blob/8c0fea059fe31da13d5113df065a7f922bd8f37e/people/stevekirk.json#L12-L15) and verify website links exist
2. Go to [profile ](https://restincode.com/memorial.html?name=stevekirk)
2. Look for any social link(s)

**Expected behavior**
A section or list should render with the various websites under "socialmedialinks"

**Screenshots**
<img width="1161" alt="Screenshot 2024-11-29 at 10 10 08 PM" src="https://github.com/user-attachments/assets/150a8adf-19da-4a40-9ca6-d3ba87a89931">

**Desktop**

- OS: macOS 15.1.1 (24B2091)
- Browser Safari 
- Version 18.1.1 (20619.2.8.11.12)

**Smartphone**

- Device: Apple iPhone 16 Pro
- OS: iOS 18.1.1
- Browser Safari
- Version Unknown

**Additional context**
The content does not render on either mobile devices or desktops.

**Comment by mauvehed** [comment]
Thank you @aghassemlouei! We will look into this.

**Comment by attritionorg** [comment]
![283-works-for-me](https://github.com/user-attachments/assets/3b8d4f02-2756-4417-9ac1-88965f83e7d7)

Win 11, Chrome (latest) and they render for me on Lockheed's page from your example. This will be a @mauvehed issue to debug next.

**Comment by mauvehed** [comment]
I am also not able to reproduce this on macOS, testing in Safari, Firefox and Chrome.

**Comment by aghassemlouei** [comment]
Apologies folks; figured out that I was being ignorant. The 1Blocker "Block Widgets" seems to affect that element as shown below: 
<img width="948" alt="Screenshot 2024-12-12 at 6 07 30 PM" src="https://github.com/user-attachments/assets/b9e62a07-548f-4640-bc78-bf9b7ae6f7a4" />
<img width="1140" alt="Screenshot 2024-12-12 at 6 07 12 PM" src="https://github.com/user-attachments/assets/8bf23663-e677-4b27-9644-b7110ebcc579" />
When the 1Blocker "Block Widgets" setting is disabled the elements render properly: 
<img width="948" alt="Screenshot 2024-12-12 at 6 02 37 PM" src="https://github.com/user-attachments/assets/8ac6ad1c-6099-4ced-8372-043bcb7cd0d0" />
<img width="1140" alt="Screenshot 2024-12-12 at 6 02 39 PM" src="https://github.com/user-attachments/assets/84e3631c-1ba4-4295-ad67-4c0c9864e33c" />
Moving forward I will be better about validating before opening up an issue.
