### ISSUE TITLE
Create a memorials template for adding people

### ISSUE THREAD

**Issue by mauvehed** [restincode/restincode#45]
Let's build and define a default template (expanded from the current being used)

                                                                                                                                               
# Firstname Lastname (Handle)

## Comments

> Lorem Ipsum - Rob Fuller

## Images

![](/images/Firstname_Lastname.jpg)

**Comment by mubix** [comment]
This should now be do-able now that this is an org project

**Comment by mauvehed** [comment]
Completed via a json file for the new sunfire layout

https://github.com/restincode/restincode/blob/master/people/_template.json
