### ISSUE TITLE
www.restincode.com does not resolve

### ISSUE THREAD

**Issue by mauvehed** [restincode/restincode#50]
Only the domain itself resolves

```
$ host restincode.com
restincode.com has address 185.199.108.153
restincode.com has address 185.199.111.153
restincode.com has address 185.199.110.153
restincode.com has address 185.199.109.153

$ host www.restincode.com
Host www.restincode.com not found: 3(NXDOMAIN)
```

**Comment by mubix** [comment]
Who uses "www" anymore ;-) I'll fix it.

**Comment by mubix** [comment]
![DNS_Fix_RIC](https://user-images.githubusercontent.com/679319/61582938-3d19e380-aaff-11e9-821e-33f10756ab86.png)

Should be fixed and propagated within 24 hours. Feel free to close @mauvehed when you can see the change.

**Comment by mubix** [comment]
Should be fixed. I updated the DNS. Please let me know if you see the change (might take 24 hours)

**Comment by mubix** [comment]
![DNS_Fix_RIC2](https://user-images.githubusercontent.com/679319/61582980-02fd1180-ab00-11e9-8748-2e32f4f5fd1d.png)

**Comment by mauvehed** [comment]
Ignore 

![image](https://user-images.githubusercontent.com/141381/61583133-823b1700-aaf9-11e9-9d2e-dd05e52dc069.png)

**Comment by mauvehed** [comment]
Working for me!
