### ISSUE TITLE
Migrate to SunFire's code base

### ISSUE THREAD

**Issue by mubix** [restincode/restincode#56]
Migrate code from https://bitbucket.org/sunfireweb/restincode/src/master/ to this repository and re-format all entries to match

**Comment by mubix** [comment]
Started this migration with 04722f92b641940618a558d6f9089cee6f5c9c95 It should be a lot easier to add people now. Once we have migrated over all of those that are already there, we can move sunfire.html to index.html and complete this ticket.

**Comment by mauvehed** [comment]
@mubix I believe this is pretty much done and ready. There's a few more Issues to add more content to the JSON files, but everyone who was in the old site should be in the new peoplelist.json. We can either make this live sooner or wait until the rest of [Milestone 1](https://github.com/restincode/restincode/milestone/1) is complete.

**Comment by mauvehed** [comment]
This is 100% ready to go live. I will create a PR to do so.
