### ISSUE TITLE
Social Media Links aren't clickable

### ISSUE THREAD

**Issue by mauvehed** [restincode/restincode#72]
This may extend to all links, but at least the social media links are not clickable on the new Sunfire theme. The highlight/color change on hover, but are can't be clicked in either Chrome or FireFox.

**Comment by attritionorg** [comment]
Confirmed on Chrome

**Comment by mubix** [comment]
Something is removing some of the special characters from the links. Not sure what it is yet

**Comment by mubix** [comment]
Fixed with 38e2030b18b00f30c3db1966537549f9770a97f7
