### ISSUE TITLE
Setup a CONTRIBUTING.md file in Github for standards documentation

### ISSUE THREAD

**Issue by mauvehed** [restincode/restincode#73]
Would be a good idea to setup a wiki with some info on standards for community submissions but also things like how to use labels and how to review PRs.

**Comment by mubix** [comment]
So Github has a default markdown file meant for contributing: https://help.github.com/en/articles/setting-guidelines-for-repository-contributors maybe we just use that setup? Or do you think a wiki would be better?

**Comment by mauvehed** [comment]
I think the contributors file will be enough. I'll modify this Issue.
