### ISSUE TITLE
auto-tweeting feedback & ideas

### ISSUE THREAD

**Issue by attritionorg** [restincode/restincode#9]
"I would also like to have the twitter account I created @RestInCode to tweet out via Lamda or whatever a reminder of dates of passing or other messages of well wishes on a regular basis."

I'd recommend pinging Steve Werby, who runs the @TodayInInfosec account which does just that. Not sure if he has it automated or if so, to what degree, but he can likely give valuable input on his experience here.

https://twitter.com/todayininfosec
https://twitter.com/stevewerby

**Comment by mubix** [comment]
Thanks! Reached out.

**Comment by devsecfranklin** [comment]
I can build some stuff for you guys if you want. :)
