### ISSUE TITLE
Profile and image layout discussion

### ISSUE THREAD

**Issue by Thaumaturgy** [restincode/restincode#92]
Would like to see a stronger layout for the photos/images - possibly moving them to the top of the page. Make them a banner/ ribbon with scroll arrows so that there are 4 photos max visible at a time. Alternatively, Create a profile picture for each person in the list and place that at the top (right or left) and then leave the images at the bottom (resized/scaled to a common size but can be selected and viewed at original size)

![profile image](https://user-images.githubusercontent.com/53869752/65047164-f9413000-d92f-11e9-853f-01e985fec192.png)

**Comment by philcryer** [comment]
Could I suggest we look at a static site content option, say Jekyll or Hugo for a reorg, or is that a separate ticket/effort?
